name: Scraping Job

on:
  schedule:
    - cron: '*/5 * * * *' # Ceci exécutera le job toutes les heures. Modifiez selon vos besoins.

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Ou la version que vous préférez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Git
      run: |
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global user.email "${{ secrets.GH_USERNAME }}@users.noreply.github.com"

    - name: Run scraper
      run: python main.py # Remplacez "votre_script.py" par le nom de votre script

    - name: Commit and push changes
      run: |
        git add data.json # Assurez-vous que cela correspond au nom de votre fichier JSON
        git pull origin master
        git commit -m "Update data.json with new scraping data" || echo "No changes to commit"
        git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/ScrappingConstantDeltarune.git
